return {
  'folke/trouble.nvim',
  enabled = false,
  opts = {
    auto_close = false,
    auto_open = false,
    auto_preview = false,
    auto_refresh = true,
    auto_jump = false,
    focus = true,
    restore = true,
    follow = true,
    indent_guides = true,
    max_items = 200,
    multiline = true,
    pinned = false,
    warn_no_results = true,
    open_no_results = false,
    keys = {
      ['?'] = 'help',
      r = 'refresh',
      R = 'toggle_refresh',
      q = 'close',
      o = 'jump_close',
      ['<esc>'] = 'cancel',
      ['<cr>'] = 'jump',
      ['<2-leftmouse>'] = 'jump',
      ['<c-s>'] = 'jump_split',
      ['<c-v>'] = 'jump_vsplit',
      -- go down to next item (accepts count)
      j = 'next',
      -- ['}'] = 'next',
      -- [']]'] = 'next',
      -- go up to prev item (accepts count)
      k = 'prev',
      -- ['{'] = 'prev',
      -- ['[['] = 'prev',
      dd = 'delete',
      d = { action = 'delete', mode = 'v' },
      i = 'inspect',
      p = 'preview',
      P = 'toggle_preview',
      zo = 'fold_open',
      zO = 'fold_open_recursive',
      zc = 'fold_close',
      zC = 'fold_close_recursive',
      za = 'fold_toggle',
      zA = 'fold_toggle_recursive',
      zm = 'fold_more',
      zM = 'fold_close_all',
      zr = 'fold_reduce',
      zR = 'fold_open_all',
      zx = 'fold_update',
      zX = 'fold_update_all',
      zn = 'fold_disable',
      zN = 'fold_enable',
      zi = 'fold_toggle_enable',
    },
  },
  keys = {
    {
      '<leader>xx',
      '<cmd>Trouble lsp_workspace_diagnostics toggle<cr>',
      desc = 'Errors',
    },
    {
      '<leader>xX',
      '<cmd>Trouble diagnostics toggle filter.buf=0<cr>',
      desc = 'Buffer Diagnostics',
    },
    {
      '<leader>cs',
      '<cmd>Trouble symbols toggle focus=false<cr>',
      desc = 'Symbols',
    },
    {
      '<leader>cl',
      '<cmd>Trouble lsp toggle focus=false win.position=right<cr>',
      desc = 'LSP Definitions / references / ...',
    },
    {
      '<leader>xL',
      '<cmd>Trouble loclist toggle<cr>',
      desc = 'Location List',
    },
    {
      '<leader>xq',
      '<cmd>Trouble qflist toggle<cr>',
      desc = 'Quickfix List',
    },
    {
      '<leader>xt',
      '<cmd>Trouble todo<cr>',
      desc = 'Todo list',
    },
  },
}
