version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ if .SSHSession }}󰖟{{ else }}@{{ end }}{{ .UserName }}'
    foreground = '#98971A'
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Name }}'
    foreground = '#B16286'
    type = 'shell'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Path }}'
    foreground = '#FABD2F'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'agnoster_short'

  [[blocks.segments]]
    template = ' 󰘬(<#D79921>{{ .HEAD }}</>){{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <#D79921>{{ .Working.String }}</>{{ end }}'
    foreground = '#83A598'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'
      fetch_status = true

  [[blocks.segments]]
    template = ' {{ .FormattedMs }}'
    foreground = '#A89984'
    type = 'executiontime'
    style = 'powerline'

    [blocks.segments.properties]
      always_enabled = false
      cache_duration = 'none'
      style = 'austin'
      threshold = 100

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    template = ' {{ .CurrentDate | date .Format }}'
    foreground = '#98971A'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      time_format = '3:04:05 PM'

  [[blocks.segments]]
    template = ' [{{ if not .Error }}{{ .Percentage }}{{ end }}%]'
    type = 'battery'
    style = 'powerline'
    foreground_templates = ['{{ if eq "Charging" .State.String }}#FABD2F{{ end }}', '{{ if eq "Discharging" .State.String }}#FB4934{{ end }}', '{{ if eq "Full" .State.String }}#B8BB26{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '>'
    foreground = '#83A598'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
