# General
"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

# Left aligned block
[[blocks]]
type = "prompt"
alignment = "left"

# User segment
[[blocks.segments]]
type = "session"
style = "plain"
template = "{{ if .SSHSession }}ssh {{ end }}{{ .UserName }}@{{ .HostName }}"
foreground = "#98971A"

# Shell segment
[[blocks.segments]]
type = "shell"
style = "powerline"
foreground = "#B16286"
template = " {{ .Name }}"

# Path segment
[[blocks.segments]]
type = "path"
style = "plain"
foreground = "#FABD2F"
template = " {{ .Path }}"

[blocks.segments.properties]
style = "agnoster_short"

# Git segment
[[blocks.segments]]
type = "git"
style = "plain"
foreground = "#83A598"
template = " git(<#D79921>{{ .HEAD }}</>){{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <#D79921>{{ .Working.String }}</>{{ end }}"

[blocks.segments.properties]
branch_icon = ""
fetch_status = true

# Execution time segment
[[blocks.segments]]
type = "executiontime"
style = "powerline"
foreground = "#A89984"
template = " {{ .FormattedMs }}"

[blocks.segments.properties]
always_enabled = false
style = "austin"
threshold = 100

# Right aligned blocks
[[blocks]]
alignment = "right"
type = "prompt"

# # Spotify block
# [[blocks.segments]]
# foreground = "#1ED760"
# style = "powerline"
# template = "{{ .Icon }}{{ if ne .Status \"stopped\" }}{{ .Artist }} - {{ .Track }}{{ end }}"
# type = "spotify"
#
# [blocks.segments.properties]
# playing_icon = " "
# paused_icon = " "
# stopped_icon = " "

# Time block
[[blocks.segments]]
type = "time"
style = "plain"
foreground = "#98971A"
template = " {{ .CurrentDate | date .Format }}"

[blocks.segments.properties]
time_format = "3:04:05 PM"

# Battery block
[[blocks.segments]]
type = "battery"
style = "powerline"
foreground_templates = [
    "{{if eq \"Charging\" .State.String}}#FABD2F{{end}}",
    "{{if eq \"Discharging\" .State.String}}#FB4934{{end}}",
    "{{if eq \"Full\" .State.String}}#B8BB26{{end}}",
]
template = " [{{ if not .Error }}{{ .Percentage }}{{ end }}%]"

[[blocks.segments]]
type = "text"
style = "plain"
foreground = "#83A598"
template = "\n$"
