export use btm-completions.nu *
export use cargo-completions.nu *
export use croc-completions.nu *
export use curl-completions.nu *
export use docker-completions.nu *
export use eza-completions.nu *
export use git-completions.nu *
export use rg-completions.nu *
export use ttyper-completions.nu *
